version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: .env
    container_name: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command:
      - postgres
      - -c
      - PORT=${POSTGRES_PORT}
    restart: on-failure

volumes:
  postgres_data:
